"""create initial mvp schema

Revision ID: 5b667e6b26e6
Revises: 
Create Date: 2026-08-12 02:48:36.628023
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5b667e6b26e6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transaction_categories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('category_type', sa.String(length=10), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("category_type IN ('income', 'expense')", name='ck_transaction_categories_category_type'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'category_type', name='uq_transaction_categories_name_type')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=150), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email', name='uq_users_email')
    )
    op.create_index('ix_users_email_lower', 'users', [sa.text('lower(email)')], unique=True)
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('action_type', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_logs_entity', 'audit_logs', ['entity_type', 'entity_id'], unique=False)
    op.create_index('ix_audit_logs_user_created_at', 'audit_logs', ['user_id', 'created_at'], unique=False)
    op.create_table('budgets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('budget_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('budget_amount >= 0', name='ck_budgets_amount_non_negative'),
    sa.CheckConstraint('period_end >= period_start', name='ck_budgets_period_valid'),
    sa.ForeignKeyConstraint(['category_id'], ['transaction_categories.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'category_id', 'period_start', 'period_end', name='uq_budgets_user_category_period')
    )
    op.create_index('ix_budgets_user_period', 'budgets', ['user_id', 'period_start', 'period_end'], unique=False)
    op.create_table('financial_accounts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('account_name', sa.String(length=150), nullable=False),
    sa.Column('account_type', sa.String(length=30), nullable=False),
    sa.Column('currency_code', sa.CHAR(length=3), server_default='GBP', nullable=False),
    sa.Column('current_balance', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('balance_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("account_type IN ('current', 'savings', 'credit_card', 'cash')", name='ck_financial_accounts_account_type'),
    sa.CheckConstraint("currency_code = 'GBP'", name='ck_financial_accounts_currency_code'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id', 'user_id', name='uq_financial_accounts_id_user_id')
    )
    op.create_index('ix_financial_accounts_user_id', 'financial_accounts', ['user_id'], unique=False)
    op.create_table('tax_calculations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('tax_year', sa.String(length=7), nullable=False),
    sa.Column('rules_version', sa.String(length=50), nullable=False),
    sa.Column('calculated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('total_income', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('total_allowances', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('taxable_income', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('income_tax_due', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('assumptions', sa.Text(), nullable=False),
    sa.Column('limitations', sa.Text(), nullable=False),
    sa.Column('calculation_details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.CheckConstraint("tax_year = '2026/27'", name='ck_tax_calculations_tax_year'),
    sa.CheckConstraint('income_tax_due >= 0', name='ck_tax_calculations_income_tax_due_non_negative'),
    sa.CheckConstraint('taxable_income >= 0', name='ck_tax_calculations_taxable_income_non_negative'),
    sa.CheckConstraint('total_allowances >= 0', name='ck_tax_calculations_allowances_non_negative'),
    sa.CheckConstraint('total_income >= 0', name='ck_tax_calculations_total_income_non_negative'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_tax_calculations_user_tax_year', 'tax_calculations', ['user_id', 'tax_year'], unique=False)
    op.create_table('financial_reports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('tax_calculation_id', sa.UUID(), nullable=True),
    sa.Column('report_type', sa.String(length=50), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('file_format', sa.String(length=10), nullable=False),
    sa.Column('storage_path', sa.Text(), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("file_format IN ('pdf', 'xlsx')", name='ck_financial_reports_file_format'),
    sa.CheckConstraint("report_type IN ('monthly_summary', 'expense_summary', 'tax_summary')", name='ck_financial_reports_report_type'),
    sa.CheckConstraint('period_end >= period_start', name='ck_financial_reports_period_valid'),
    sa.ForeignKeyConstraint(['tax_calculation_id'], ['tax_calculations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_financial_reports_user_generated_at', 'financial_reports', ['user_id', 'generated_at'], unique=False)
    op.create_table('transactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=True),
    sa.Column('transaction_date', sa.Date(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('transaction_type', sa.String(length=10), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('source_reference', sa.String(length=255), nullable=True),
    sa.Column('is_reviewed', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("source IN ('csv', 'sample')", name='ck_transactions_source'),
    sa.CheckConstraint("transaction_type IN ('income', 'expense')", name='ck_transactions_transaction_type'),
    sa.CheckConstraint('amount > 0', name='ck_transactions_amount_positive'),
    sa.CheckConstraint('length(trim(description)) > 0', name='ck_transactions_description_not_blank'),
    sa.ForeignKeyConstraint(['account_id', 'user_id'], ['financial_accounts.id', 'financial_accounts.user_id'], name='fk_transactions_account_id_user_id_financial_accounts'),
    sa.ForeignKeyConstraint(['category_id'], ['transaction_categories.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'source_reference', name='uq_transactions_account_source_reference')
    )
    op.create_index('ix_transactions_account_transaction_date', 'transactions', ['account_id', 'transaction_date'], unique=False)
    op.create_index('ix_transactions_category_id', 'transactions', ['category_id'], unique=False)
    op.create_index('ix_transactions_user_transaction_date', 'transactions', ['user_id', 'transaction_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_transactions_user_transaction_date', table_name='transactions')
    op.drop_index('ix_transactions_category_id', table_name='transactions')
    op.drop_index('ix_transactions_account_transaction_date', table_name='transactions')
    op.drop_table('transactions')
    op.drop_index('ix_financial_reports_user_generated_at', table_name='financial_reports')
    op.drop_table('financial_reports')
    op.drop_index('ix_tax_calculations_user_tax_year', table_name='tax_calculations')
    op.drop_table('tax_calculations')
    op.drop_index('ix_financial_accounts_user_id', table_name='financial_accounts')
    op.drop_table('financial_accounts')
    op.drop_index('ix_budgets_user_period', table_name='budgets')
    op.drop_table('budgets')
    op.drop_index('ix_audit_logs_user_created_at', table_name='audit_logs')
    op.drop_index('ix_audit_logs_entity', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index('ix_users_email_lower', table_name='users')
    op.drop_table('users')
    op.drop_table('transaction_categories')
    # ### end Alembic commands ###
