"""Financial report generation and retrieval endpoints."""

from __future__ import annotations

from typing import Annotated
from uuid import UUID

from fastapi import APIRouter, Depends, HTTPException, status
from sqlalchemy.orm import Session

from app.api.dependencies import get_current_user, get_db
from app.db.models import User
from app.db.repositories.financial_report_repository import FinancialReportRepository
from app.schemas.report import ReportGenerateRequest, ReportDetailResponse, ReportResponse
from app.services.report_service import ReportService

router = APIRouter(prefix="/reports", tags=["Reports"])


@router.post(
    "/generate",
    response_model=ReportDetailResponse,
    status_code=status.HTTP_201_CREATED,
    summary="Generate a financial report for a given period",
)
def generate_report(
    payload: ReportGenerateRequest,
    current_user: Annotated[User, Depends(get_current_user)],
    db: Annotated[Session, Depends(get_db)],
) -> ReportDetailResponse:
    """Generate a PDF financial report for the authenticated user.

    The report includes:
    - Total income and expenses for the period
    - Net amount
    - Expense breakdown by category
    - Transaction count
    - Financial disclaimer

    Supported report types: monthly_summary, expense_summary, tax_summary.
    """
    repo = FinancialReportRepository(db)
    service = ReportService(db, repo)
    try:
        return service.generate_report(
            user_id=current_user.id,
            user_email=current_user.email,
            payload=payload,
        )
    except ValueError as exc:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail=str(exc),
        ) from exc


@router.get(
    "",
    response_model=list[ReportResponse],
    status_code=status.HTTP_200_OK,
    summary="List all generated reports for the authenticated user",
)
def list_reports(
    current_user: Annotated[User, Depends(get_current_user)],
    db: Annotated[Session, Depends(get_db)],
) -> list[ReportResponse]:
    """List all financial reports generated by the authenticated user, newest first."""
    repo = FinancialReportRepository(db)
    service = ReportService(db, repo)
    return service.list_reports(user_id=current_user.id)


@router.get(
    "/{report_id}",
    response_model=ReportResponse,
    status_code=status.HTTP_200_OK,
    summary="Get a specific report by ID",
)
def get_report(
    report_id: UUID,
    current_user: Annotated[User, Depends(get_current_user)],
    db: Annotated[Session, Depends(get_db)],
) -> ReportResponse:
    """Retrieve a specific report by ID, ensuring it belongs to the authenticated user."""
    repo = FinancialReportRepository(db)
    service = ReportService(db, repo)
    result = service.get_report(user_id=current_user.id, report_id=report_id)
    if result is None:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="Report not found or access denied.",
        )
    return result
